/* tslint:disable */
/* eslint-disable */
// @ts-nocheck
//
// THIS IS A GENERATED FILE
// DO NOT MODIFY IT! YOUR CHANGES WILL BE LOST
export enum TaskStatus {
  TASK_STATUS_UNSPECIFIED = 0,
  TASK_STATUS_CREATING = 1,
  TASK_STATUS_SUBMITTED = 2,
  TASK_STATUS_DISPATCHED = 3,
  TASK_STATUS_COMPLETED = 4,
  TASK_STATUS_ERROR = 5,
  TASK_STATUS_TIMEOUT = 6,
  TASK_STATUS_CANCELLING = 7,
  TASK_STATUS_CANCELLED = 8,
  TASK_STATUS_PROCESSING = 9,
  TASK_STATUS_PROCESSED = 10
}
