export enum TaskStatus {
  UNSPECIFIED = 0,
  CREATING = 1,
  SUBMITTED = 2,
  DISPATCHED = 3,
  COMPLETED = 4,
  ERROR = 5,
  TIMEOUT = 6,
  CANCELLING = 7,
  CANCELLED = 8,
  PROCESSING = 9,
  PROCESSED = 10,
}
