name: ci libs ui
on:
  push:
    branches-ignore:
      - "main"
    paths:
      - "libs/ui/**"
  pull_request:
    branches:
      - "main"
      - "develop"
    paths:
      - "libs/ui/**"

env:
  NODE_VERSION: 16
jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Set up Node
        uses: actions/setup-node@v2
        with:
          node-version: ${{ env.NODE_VERSION }}
          check-latest: true
          cache: npm

      - name: Cache Node modules
        id: cache-node-modules
        uses: actions/cache@v2
        with:
          path: node_modules
          key: ${{ runner.os }}-${{ hashFiles('**/package-lock.json') }}

      - name: Install dependencies
        if: steps.cache-node-modules.outputs.cache-hit != 'true'
        run: npm ci

      - name: Cache setup
        uses: actions/cache@v2
        with:
          path: ./*
          key: ${{ github.sha }}

  run:
    needs: setup
    runs-on: ubuntu-latest
    strategy:
      matrix:
        command:
          - lint ui
          - test ui
    steps:
      - name: Restore setup
        uses: actions/cache@v2
        with:
          path: ./*
          key: ${{ github.sha }}

      - name: Set up Node
        uses: actions/setup-node@v2
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Run ${{ matrix.command }}
        run: npx -y nx ${{ matrix.command }}
