name: CI

on:
  push:
    branches:
      - 'main'
      - 'v**'
  pull_request:
    branches:
      - 'main'
      - 'v**'

concurrency:
  group: ${{ github.workflow }}-${{ github.event.number || github.sha }}
  cancel-in-progress: ${{ github.event_name != 'push' }}

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@eef61447b9ff4aafe5dcd4e0bbf5d482be7e7871 # v4

      - run: npm install -g pnpm@9.7.0
      - run: corepack enable

      - name: Setup Node
        uses: actions/setup-node@0a44ba7841725637a19e28fa30b79a866c81b0a6 # v4
        with:
          node-version: 20
          cache: pnpm

      - name: Install dependencies
        run: pnpm install

      - name: Lint
        run: pnpm lint

  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@eef61447b9ff4aafe5dcd4e0bbf5d482be7e7871 # v4
      
      - run: npm install -g pnpm@9.7.0
      - run: corepack enable

      - uses: actions/setup-node@0a44ba7841725637a19e28fa30b79a866c81b0a6 # v4
        with:
          node-version: 20
          cache: pnpm

      - name: Install dependencies
        run: pnpm install

      - name: Test
        run: pnpm test

  coverage:
    name: Coverage
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@eef61447b9ff4aafe5dcd4e0bbf5d482be7e7871 # v4
      
      - run: npm install -g pnpm@9.7.0
      - run: corepack enable

      - uses: actions/setup-node@0a44ba7841725637a19e28fa30b79a866c81b0a6 # v4
        with:
          node-version: 20
          cache: pnpm

      - name: Install dependencies
        run: pnpm install

      - name: Test
        run: pnpm test-coverage-ci

      - name: Coverage
        if: always()
        uses: MishaKav/jest-coverage-comment@main
        with:
          junitxml-title: JUnit
          junitxml-path: ./junit.xml
          coverage-title: Files coverage
          coverage-path: ./coverage.txt

  build:
    
    name: Build
    runs-on: ubuntu-latest
    steps:
      
      - uses: actions/checkout@eef61447b9ff4aafe5dcd4e0bbf5d482be7e7871 # v4

      - run: npm install -g pnpm@9.7.0
      - run: corepack enable

      - uses: actions/setup-node@0a44ba7841725637a19e28fa30b79a866c81b0a6 # v4
        with:
          node-version: 20
          cache: pnpm

      - name: Install dependencies
        run: pnpm install

      - name: Build
        run: pnpm build

 