name: Release Edge Images

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  build-push-docker-images:
    name: Build and Push Docker Images
    runs-on: ubuntu-latest
    strategy:
      matrix:
        dockerfile:
          - name: armonik_admin_app
            file: app.Dockerfile

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - run: npm install -g pnpm @antfu/ni

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
          cache: "pnpm"

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v3
        with:
          # list of Docker images to use as base name for tags
          images: |
            dockerhubaneo/${{ matrix.dockerfile.name }}
          # generate Docker tags based on the following events/attributes
          tags: |
            type=ref,event=pr
            type=edge,branch=main

      - name: Login to DockerHub
        if: github.event_name != 'push'
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USER }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          push: ${{ github.event_name != 'push' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          file: ${{ matrix.dockerfile.file }}
          cache-from: type=registry,ref=dockerhubaneo/${{ matrix.dockerfile.name }}:buildcache
          cache-to: type=registry,ref=dockerhubaneo/${{ matrix.dockerfile.name }}:buildcache,mode=max
